<?php
// v3 — + clé mdp_oublie
// membre/lang.php — Traductions pour l'espace membre
// Inclure après session_start()

// Priorité : param GET ?lang= > session membre_lang > session LANG (site principal) > FR
if (session_status() === PHP_SESSION_NONE) session_start();
if (!empty($_GET['lang']) && in_array($_GET['lang'], ['fr','nl'])) {
    $_SESSION['membre_lang'] = $_GET['lang'];
}
$LANG = $_SESSION['membre_lang'] ?? $_SESSION['app_lang'] ?? 'fr';

// ── Dictionnaire ──────────────────────────────────────────────────────────
$T = $LANG === 'nl' ? [

  // Titres & nav
  'site_title'          => 'Ça suffit ! VZW',
  'retour_site'         => '← Terug naar de site',
  'retour_espace'       => '← Terug naar mijn ruimte',

  // Inscription
  'inscription_titre'   => 'Uw ledenruimte aanmaken',
  'inscription_page'    => 'Lid worden — Ça suffit ! VZW',
  'avantages_intro'     => 'Door lid te worden krijgt u:',
  'avantage_qr'         => 'Een persoonlijke QR-code met gestructureerde mededeling (+++)',
  'avantage_dons'       => 'Het overzicht van uw giften in uw privéruimte',
  'avantage_nl'         => 'De nieuwsbrief om op de hoogte te blijven van onze acties',
  'avantage_acces'      => 'Beveiligde toegang via magische link (zonder wachtwoord)',
  'prenom'              => 'Voornaam *',
  'nom'                 => 'Naam *',
  'email'               => 'E-mail *',
  'adresse'             => 'Adres (straat en nummer)',
  'adresse_ph'          => 'Leliestraat 42',
  'commune'             => 'Gemeente',
  'commune_ph'          => 'Waterloo',
  'telephone'           => 'Telefoon',
  'telephone_ph'        => '+32 470 00 00 00',
  'rgpd_label'          => 'Ik ga akkoord dat mijn gegevens worden gebruikt door de VZW <strong>Ça suffit !</strong> (Baan 01 · UBCNA) overeenkomstig de AVG. Ik kan me op elk moment uitschrijven vanuit mijn ledenruimte.',
  'captcha_label'       => '🤖 Anti-robotverificatie *',
  'btn_creer'           => 'Mijn ledenruimte aanmaken →',
  'deja_membre'         => 'Al lid?',
  'recevoir_lien'       => 'Mijn aanmeldingslink ontvangen',
  'msg_bienvenue'       => 'Welkom! 🎉 Uw ledenaccount <strong>%s</strong> is aangemaakt.<br>Een aanmeldingslink is verzonden naar <strong>%s</strong>. Controleer uw spam indien nodig.',
  'msg_deja_membre'     => 'U bent al lid! Een aanmeldingslink is verzonden naar <strong>%s</strong>.',
  'err_email'           => 'Ongeldig e-mailadres.',
  'err_prenom_nom'      => 'Voornaam en naam zijn verplicht.',
  'err_adresse'         => 'Het adres is verplicht.',
  'err_rgpd'            => 'U moet het AVG-beleid aanvaarden.',
  'err_captcha'         => 'Fout antwoord op de anti-robotverificatie. Probeer opnieuw.',
  'err_rate_limit'      => 'Te veel pogingen. Probeer over een uur opnieuw.',
  'err_securite'        => 'Beveiligingsfout. Herlaad de pagina en probeer opnieuw.',
  'err_creation'        => 'Fout bij het aanmaken van het account.',

  // Login
  'login_titre'         => 'Toegang ledenruimte',
  'login_page'          => 'Aanmelding lid — Ça suffit ! VZW',
  'login_explain'       => 'Voer uw e-mail in en wij sturen u een <strong>beveiligde aanmeldingslink</strong> geldig 24u. Geen wachtwoord te onthouden!',
  'votre_email'         => 'Uw e-mailadres',
  'btn_recevoir_lien'   => '✉ Mijn aanmeldingslink ontvangen',
  'pas_encore_membre'   => 'Nog geen lid?',
  'creer_espace'        => 'Mijn ledenruimte aanmaken',
  'msg_lien_envoye'     => 'Een aanmeldingslink is verzonden naar <strong>%s</strong>.<br>Deze link is geldig <strong>24 uur</strong>. Controleer uw spam indien nodig.',
  'msg_lien_generique'  => 'Als dit e-mailadres overeenkomt met een actief ledenaccount, is een aanmeldingslink verzonden.',
  'err_email_invalide'  => 'Ongeldig e-mailadres.',

  // Magic link
  'magic_page'          => 'Aanmelding — Ça suffit ! VZW',
  'lien_invalide_titre' => 'Ongeldige of verlopen link',
  'lien_invalide_msg'   => 'Deze link is ongeldig of verlopen. <a href="login.php">Vraag een nieuwe link aan</a>.',
  'btn_new_lien'        => 'Een nieuwe link aanvragen',

  // Confirm email
  'confirm_invalide_h'  => 'Ongeldige link',
  'confirm_invalide_p'  => 'Deze bevestigingslink is ongeldig of al gebruikt.',
  'confirm_ok_h'        => '✓ E-mail bevestigd',
  'confirm_ok_p'        => 'Uw e-mail is bijgewerkt naar <strong>%s</strong>.',
  'retour_espace_btn'   => '← Mijn ledenruimte',

  // Profil
  'profil_page'         => 'Mijn profiel — Ça suffit ! VZW',
  'profil_titre'        => 'Mijn profiel',
  'identite'            => 'Identiteit',
  'contact'             => 'Contact',
  'adresse_section'     => 'Adres',
  'rue_numero'          => 'Straat en nummer',
  'code_postal'         => 'Postcode',
  'email_warn'          => '⚠ Het wijzigen van het e-mailadres verandert ook uw aanmeldingsadres via magische link.',
  'btn_enregistrer'     => '💾 Wijzigingen opslaan',
  'msg_profil_ok'       => 'Uw gegevens zijn opgeslagen.',
  'err_champs_req'      => 'Voornaam, naam en e-mail zijn verplicht.',
  'err_email_invalide2' => 'Ongeldig e-mailadres.',
  'err_email_pris'      => 'Dit e-mailadres is al in gebruik door een ander account.',
  'info_membre'         => '🪪 Lidnummer: %s',
  'cree_le'             => 'Aangemaakt op %s',

  // Dashboard (utilisé dans dashboard.php)
  'dashboard_page'      => 'Mijn ruimte — Ça suffit ! VZW',
  'back_site'           => '← Hoofdsite',
  'bonjour'             => 'Hallo',
  'membre_depuis'       => 'Lid',
  'tab_dons'            => '💶 Mijn giften',
  'tab_profil'          => '👤 Mijn profiel',
  'tab_nl'              => '📰 Nieuwsbrief',
  'generer_qr'          => '💶 Een betalings-QR genereren',
  'deconnexion'         => 'Afmelden',
  'msg_profil_maj'      => '✓ Uw gegevens zijn opgeslagen.',
  'msg_qr_genere'       => '✓ QR-code gegenereerd — scan om te betalen.',
  'msg_don_supprime'    => '✓ QR-code / gift verwijderd.',
  'msg_desabonne'       => '✓ Uitgeschreven van de nieuwsbrief.',
  'msg_reabonne'        => '✓ Opnieuw ingeschreven voor de nieuwsbrief.',
  'err_email_inv'       => '✗ Ongeldig e-mailadres.',
  'err_email_pris2'     => '✗ Dit e-mailadres is al in gebruik door een ander account.',
  'err_rgpd_req'        => '⚠ AVG-toestemming vereist',
  'selecteur_lang'      => 'FR | NL',
  // Dashboard — textes supplémentaires
  'msg_email_confirm'   => '📧 Een bevestigingslink is verzonden naar uw nieuw e-mailadres. Klik erop om de wijziging te valideren.',
  'banner_rgpd_txt'     => 'Gelieve de voorwaarden voor de opslag van uw gegevens te lezen en te aanvaarden in het tabblad <strong>Mijn profiel</strong>.',
  'banner_maj_txt'      => 'Uw gegevens zijn meer dan een jaar niet gecontroleerd. Gelieve ze te bevestigen of bij te werken.',
  'btn_maj'             => 'Bijwerken',
  'qr_actif'            => '📱 Actieve QR-code',
  'btn_generer_qr'      => '✨ Mijn QR-code genereren',
  'qr_hint'             => 'Een QR-code met uw unieke gestructureerde mededeling wordt gegenereerd. Scan met uw bank-app.',
  'recurrent_title'     => 'Hebt u een automatische overschrijving?',
  'recurrent_text'      => 'Als u de vereniging steunt via een doorlopende opdracht (terugkerende overschrijving), vermeld dan uw lidnummer in de mededeling. Zo kunnen wij elke storting aan uw account koppelen zonder enige stap van uw kant.',
  'recurrent_comm_label'=> 'Te vermelden in de mededeling:',
  'suppr_don_titre'     => 'Deze onbetaalde QR / gift verwijderen',
  'suppr_don_confirm'   => 'Deze QR-code verwijderen? Als u die niet hebt gebruikt om te betalen, kunt u die veilig verwijderen. Deze actie is definitief.',
  'qr_placeholder'      => 'Kies een bedrag<br>en genereer uw QR →',
  'historique_dons'     => '📋 Overzicht van mijn giften',
  'aucun_don'           => 'Geen geregistreerde gift.',
  'clic_qr'             => 'Klik om de QR te tonen',
  'mes_contributions'   => '📊 Mijn bijdragen',
  'total_confirme'      => 'Bevestigd totaal',
  'dons_count'          => 'Gift(en)',
  'objectif_pct'        => '% van de doelstelling',
  'newsletter_titre'    => '📧 Nieuwsbrief',
  'abonne'              => 'Ingeschreven',
  'non_abonne'          => 'Niet ingeschreven',
  'se_desabonner'       => 'Uitschrijven',
  'se_reabonner'        => 'Opnieuw inschrijven',
      // ── Invitation depuis abonné ─────────────────────────────────────────────
    'invite_bienvenue'  => 'Bonjour %s, vous êtes déjà abonné(e) à notre newsletter.',
    'invite_abonn'      => 'cher(e) abonné(e)',
    'invite_invalid'    => "Ce lien d\'invitation est invalide ou expiré (valable 30 jours).",

    'confirm_desabo'      => 'Uitschrijven?',
  'mes_donnees'         => '👤 Mijn persoonlijke gegevens',
  'section_identite'    => 'Identiteit',
  'label_prenom'        => 'Voornaam *',
  'label_nom'           => 'Naam',
  'label_tel'           => 'Telefoon',
  'section_adresse'     => 'Adres',
  'label_rue'           => 'Straat',
  'label_numero'        => 'Nr.',
  'label_boite'         => 'Bus',
  'label_cp'            => 'Postcode',
  'label_commune'       => 'Gemeente',
  'label_iban'          => 'IBAN',
  'iban_titre'          => '🏦 Rekeningnummer (optioneel — vrijwillig)',
  'iban_txt'            => 'Als u eerder giften heeft gedaan via een eenvoudige overschrijving, kunt u hier uw IBAN opgeven. Dit stelt ons in staat deze betalingen te koppelen aan uw ledenaccount. Deze informatie is strikt vertrouwelijk en wordt nooit aan derden doorgegeven.',
  'rgpd_dash_label'     => 'Ik machtig <strong>Ça suffit ! VZW</strong> om mijn persoonlijke gegevens (naam, adres, e-mail, telefoon, IBAN indien opgegeven) te registreren en verwerken in het kader van ledenbeheer en nieuwsbrief. Deze gegevens worden niet aan derden doorgegeven. Ik kan te allen tijde verwijdering aanvragen.',
  'rgpd_accepte_le'     => '✓ Aanvaard op %s',
  'derniere_verif'      => 'Laatste controle: %s',
  'btn_enregistrer_donnees' => '💾 Mijn gegevens opslaan',
  'modifier_email'      => '📧 Mijn e-mailadres wijzigen',
  // Wachtwoord
  'login_tab_pass'      => 'Wachtwoord',
  'login_tab_lien'      => 'Link per e-mail',
  'login_pass_explain'  => 'Meld u aan met uw e-mail en wachtwoord. Nog geen wachtwoord? Gebruik het tabblad "Link per e-mail".',
  'label_password'      => 'Wachtwoord',
  'btn_connexion_pass'  => 'Aanmelden',
  'mdp_oublie'          => 'Wachtwoord vergeten? Ontvang een aanmeldingslink per e-mail',
  'err_login_pass'      => 'Onjuist e-mailadres of wachtwoord.',
  'section_motdepasse'  => '🔑 Wachtwoord',
  'pass_defini'         => 'Een wachtwoord is ingesteld. U kunt zich aanmelden met e-mail + wachtwoord, of nog steeds via een magische link.',
  'pass_aucun'          => 'Geen wachtwoord ingesteld — u meldt zich aan via een magische link. U kunt hieronder een wachtwoord aanmaken.',
  'label_new_pass'      => 'Nieuw wachtwoord',
  'label_confirm_pass'  => 'Bevestig wachtwoord',
  'pass_hint'           => 'Minstens 8 tekens.',
  'btn_definir_pass'    => '🔑 Mijn wachtwoord instellen / wijzigen',
  'msg_password_ok'     => '✓ Uw wachtwoord is opgeslagen.',
  'err_pass_court'      => 'Het wachtwoord moet minstens 8 tekens bevatten.',
  'err_pass_mismatch'   => 'De twee wachtwoorden komen niet overeen.',
  'email_actuel'        => 'Huidig e-mailadres:',
  'email_en_attente'    => 'Wacht op validatie:',
  'email_nouveau_ph'    => 'Nieuw e-mailadres',
  'btn_envoyer_confirm' => 'Bevestigingslink verzenden',
  'email_confirm_hint'  => 'Een bevestigingse-mail wordt verzonden naar het nieuwe adres. De wijziging wordt van kracht na validatie.',
  'danger_titre'        => '⚠ Mijn account verwijderen',
  'danger_txt'          => 'Uw persoonlijke gegevens (naam, adres, telefoon, IBAN) worden gewist. Uw giftengeschiedenis wordt anoniem bewaard voor onze wettelijke boekhoudkundige verplichtingen. <strong>Deze actie is onomkeerbaar.</strong>',
  'btn_demander_suppression' => 'Verwijdering van mijn account aanvragen',
  'confirm_suppression_label' => 'Typ VERWIJDEREN om te bevestigen:',
  'confirm_suppression_ph'    => 'VERWIJDEREN',
  'btn_supprimer'       => '🗑 Definitief verwijderen',
  'btn_annuler'         => 'Annuleren',
  'btn_deconnecter'     => '⎋ Afmelden',
  'actualiser_qr'       => '🔄 Vernieuwen',
  'telecharger_qr'      => '⬇ Downloaden',
  'libre'               => 'Vrij bedrag',
  'montant_ph'          => 'Bedrag €',

] : [

  // Titres & nav
  'site_title'          => 'Piste01 Ça Suffit ASBL',
  'retour_site'         => '← Retour au site',
  'retour_espace'       => '← Retour à mon espace',

  // Inscription
  'inscription_titre'   => 'Créer votre espace membre',
  'inscription_page'    => 'Devenir membre — Piste01 Ça Suffit ASBL',
  'avantages_intro'     => 'En devenant membre vous obtenez :',
  'avantage_qr'         => 'Un QR code personnel avec communication structurée (+++)',
  'avantage_dons'       => 'L\'historique de vos dons dans votre espace privé',
  'avantage_nl'         => 'La newsletter pour rester informé(e) de nos actions',
  'avantage_acces'      => 'Accès sécurisé par lien magique (sans mot de passe)',
  'prenom'              => 'Prénom *',
  'nom'                 => 'Nom *',
  'email'               => 'Email *',
  'adresse'             => 'Adresse (rue et numéro)',
  'adresse_ph'          => 'Rue des Lilas 42',
  'commune'             => 'Commune',
  'commune_ph'          => 'Waterloo',
  'telephone'           => 'Téléphone',
  'telephone_ph'        => '+32 470 00 00 00',
  'rgpd_label'          => 'J\'accepte que mes données soient utilisées par l\'ASBL <strong>Ça suffit !</strong> (Piste 01 · UBCNA) conformément au RGPD. Je peux me désabonner à tout moment depuis mon espace membre.',
  'captcha_label'       => '🤖 Vérification anti-robot *',
  'btn_creer'           => 'Créer mon espace membre →',
  'deja_membre'         => 'Déjà membre ?',
  'recevoir_lien'       => 'Recevoir mon lien de connexion',
  'msg_bienvenue'       => 'Bienvenue ! 🎉 Votre compte membre <strong>%s</strong> a été créé.<br>Un lien de connexion a été envoyé à <strong>%s</strong>. Vérifiez vos spams si nécessaire.',
  'msg_deja_membre'     => 'Vous êtes déjà membre ! Un lien de connexion a été envoyé à <strong>%s</strong>.',
  'err_email'           => 'Adresse email invalide.',
  'err_prenom_nom'      => 'Prénom et nom sont obligatoires.',
  'err_adresse'         => 'L\'adresse est obligatoire.',
  'err_rgpd'            => 'Vous devez accepter la politique RGPD.',
  'err_captcha'         => 'Réponse incorrecte à la vérification anti-robot. Réessayez.',
  'err_rate_limit'      => 'Trop de tentatives. Réessayez dans une heure.',
  'err_securite'        => 'Erreur de sécurité. Rechargez la page et réessayez.',
  'err_creation'        => 'Erreur lors de la création du compte.',

  // Login
  'login_titre'         => 'Accès espace membre',
  'login_page'          => 'Connexion membre — Piste01 Ça Suffit ASBL',
  'login_explain'       => 'Entrez votre email et nous vous enverrons un <strong>lien de connexion sécurisé</strong> valable 24h. Pas de mot de passe à retenir !',
  'votre_email'         => 'Votre adresse email',
  'btn_recevoir_lien'   => '✉ Recevoir mon lien de connexion',
  'pas_encore_membre'   => 'Pas encore membre ?',
  'creer_espace'        => 'Créer mon espace membre',
  'msg_lien_envoye'     => 'Un lien de connexion a été envoyé à <strong>%s</strong>.<br>Ce lien est valable <strong>24 heures</strong>. Vérifiez vos spams si nécessaire.',
  'msg_lien_generique'  => 'Si cet email correspond à un compte membre actif, un lien de connexion a été envoyé.',
  'err_email_invalide'  => 'Adresse email invalide.',

  // Magic link
  'magic_page'          => 'Connexion — Piste01 Ça Suffit ASBL',
  'lien_invalide_titre' => 'Lien invalide ou expiré',
  'lien_invalide_msg'   => 'Ce lien est invalide ou a expiré. <a href="login.php">Demandez un nouveau lien</a>.',
  'btn_new_lien'        => 'Demander un nouveau lien',

  // Confirm email
  'confirm_invalide_h'  => 'Lien invalide',
  'confirm_invalide_p'  => 'Ce lien de confirmation est invalide ou a déjà été utilisé.',
  'confirm_ok_h'        => '✓ Email confirmé',
  'confirm_ok_p'        => 'Votre email a été mis à jour vers <strong>%s</strong>.',
  'retour_espace_btn'   => '← Mon espace membre',

  // Profil
  'profil_page'         => 'Mon profil — Piste01 Ça Suffit ASBL',
  'profil_titre'        => 'Mon profil',
  'identite'            => 'Identité',
  'contact'             => 'Contact',
  'adresse_section'     => 'Adresse',
  'rue_numero'          => 'Rue et numéro',
  'code_postal'         => 'Code postal',
  'email_warn'          => '⚠ Modifier l\'email changera aussi votre adresse de connexion par lien magique.',
  'btn_enregistrer'     => '💾 Enregistrer les modifications',
  'msg_profil_ok'       => 'Vos informations ont bien été mises à jour.',
  'err_champs_req'      => 'Prénom, nom et email sont obligatoires.',
  'err_email_invalide2' => 'Adresse email invalide.',
  'err_email_pris'      => 'Cette adresse email est déjà utilisée par un autre compte.',
  'info_membre'         => '🪪 Numéro de membre : %s',
  'cree_le'             => 'Créé le %s',

  // Dashboard
  'dashboard_page'      => 'Mon espace — Piste01 Ça Suffit ASBL',
  'back_site'           => '← Site principal',
  'bonjour'             => 'Bonjour',
  'membre_depuis'       => 'Membre',
  'tab_dons'            => '💶 Mes dons',
  'tab_profil'          => '👤 Mon profil',
  'tab_nl'              => '📰 Newsletter',
  'generer_qr'          => '💶 Générer un QR de paiement',
  'deconnexion'         => 'Déconnexion',
  'msg_profil_maj'      => '✓ Vos données ont été enregistrées.',
  'msg_qr_genere'       => '✓ QR code généré — scannez pour payer.',
  'msg_don_supprime'    => '✓ QR code / don supprimé.',
  'msg_desabonne'       => '✓ Désabonné(e) de la newsletter.',
  'msg_reabonne'        => '✓ Réabonné(e) à la newsletter.',
  'err_email_inv'       => '✗ Adresse email invalide.',
  'err_email_pris2'     => '✗ Cette adresse email est déjà utilisée par un autre compte.',
  'err_rgpd_req'        => '⚠ Consentement RGPD requis',
  'selecteur_lang'      => 'FR | NL',
  // Dashboard — textes supplémentaires
  'msg_email_confirm'   => '📧 Un lien de confirmation a été envoyé à votre nouvel email. Cliquez dessus pour valider le changement.',
  'banner_rgpd_txt'     => 'Merci de lire et d\'accepter les conditions d\'enregistrement de vos données dans l\'onglet <strong>Mon profil</strong>.',
  'banner_maj_txt'      => 'Vos données n\'ont pas été vérifiées depuis plus d\'un an. Merci de les confirmer ou mettre à jour.',
  'btn_maj'             => 'Mettre à jour',
  'qr_actif'            => '📱 QR code actif',
  'btn_generer_qr'      => '✨ Générer mon QR code',
  'qr_hint'             => 'Un QR code avec votre communication structurée unique est généré. Scannez avec votre app bancaire.',
  'recurrent_title'     => 'Vous avez un virement automatique ?',
  'recurrent_text'      => 'Si vous soutenez l\'association par un ordre permanent (virement récurrent), indiquez votre numéro de membre en communication. Cela nous permet de rattacher chaque versement à votre compte sans démarche de votre part.',
  'recurrent_comm_label'=> 'À mettre en communication :',
  'suppr_don_titre'     => 'Supprimer ce QR / don non payé',
  'suppr_don_confirm'   => 'Supprimer ce QR code ? Si vous ne l\'avez pas utilisé pour payer, vous pouvez le supprimer sans risque. Cette action est définitive.',
  'qr_placeholder'      => 'Choisissez un montant<br>et générez votre QR →',
  'historique_dons'     => '📋 Historique de mes dons',
  'aucun_don'           => 'Aucun don enregistré.',
  'clic_qr'             => 'Cliquez pour afficher le QR',
  'mes_contributions'   => '📊 Mes contributions',
  'total_confirme'      => 'Total confirmé',
  'dons_count'          => 'Don(s)',
  'objectif_pct'        => '% de l\'objectif',
  'newsletter_titre'    => '📧 Newsletter',
  'abonne'              => 'Abonné(e)',
  'non_abonne'          => 'Non abonné(e)',
  'se_desabonner'       => 'Se désabonner',
  'se_reabonner'        => 'Se réabonner',
  'confirm_desabo'      => 'Se désabonner ?',
  'mes_donnees'         => '👤 Mes données personnelles',
  'section_identite'    => 'Identité',
  'label_prenom'        => 'Prénom *',
  'label_nom'           => 'Nom',
  'label_tel'           => 'Téléphone',
  'section_adresse'     => 'Adresse',
  'label_rue'           => 'Rue',
  'label_numero'        => 'N°',
  'label_boite'         => 'Boîte',
  'label_cp'            => 'Code postal',
  'label_commune'       => 'Commune',
  'label_iban'          => 'IBAN',
  'iban_titre'          => '🏦 Numéro de compte (optionnel — sur base volontaire)',
  'iban_txt'            => 'Si vous avez effectué des dons antérieurs par virement simple, vous pouvez indiquer votre IBAN ici. Cela nous permet de relier ces versements à votre compte membre. Cette information est strictement confidentielle et ne sera jamais transmise à des tiers.',
  'rgpd_dash_label'     => 'J\'autorise <strong>Piste01 Ça Suffit ASBL</strong> à enregistrer et traiter mes données personnelles (nom, adresse, email, téléphone, IBAN si fourni) dans le cadre de la gestion des membres et de la newsletter. Ces données ne sont pas transmises à des tiers. Je peux en demander la suppression à tout moment.',
  'rgpd_accepte_le'     => '✓ Accepté le %s',
  'derniere_verif'      => 'Dernière vérification : %s',
  'btn_enregistrer_donnees' => '💾 Enregistrer mes données',
  'modifier_email'      => '📧 Modifier mon adresse email',
  // Mot de passe
  'login_tab_pass'      => 'Mot de passe',
  'login_tab_lien'      => 'Lien par email',
  'login_pass_explain'  => 'Connectez-vous avec votre email et votre mot de passe. Pas encore de mot de passe ? Utilisez l\'onglet « Lien par email ».',
  'label_password'      => 'Mot de passe',
  'btn_connexion_pass'  => 'Se connecter',
  'mdp_oublie'          => 'Mot de passe oublié ? Recevez un lien de connexion par email',
  'err_login_pass'      => 'Email ou mot de passe incorrect.',
  'section_motdepasse'  => '🔑 Mot de passe',
  'pass_defini'         => 'Un mot de passe est défini. Vous pouvez vous connecter avec email + mot de passe, ou toujours par lien magique.',
  'pass_aucun'          => 'Aucun mot de passe défini — vous vous connectez par lien magique. Vous pouvez en créer un ci-dessous.',
  'label_new_pass'      => 'Nouveau mot de passe',
  'label_confirm_pass'  => 'Confirmer le mot de passe',
  'pass_hint'           => '8 caractères minimum.',
  'btn_definir_pass'    => '🔑 Définir / changer mon mot de passe',
  'msg_password_ok'     => '✓ Votre mot de passe a été enregistré.',
  'err_pass_court'      => 'Le mot de passe doit contenir au moins 8 caractères.',
  'err_pass_mismatch'   => 'Les deux mots de passe ne correspondent pas.',
  'email_actuel'        => 'Email actuel :',
  'email_en_attente'    => 'En attente de validation :',
  'email_nouveau_ph'    => 'Nouvel email',
  'btn_envoyer_confirm' => 'Envoyer le lien de confirmation',
  'email_confirm_hint'  => 'Un email de confirmation sera envoyé à la nouvelle adresse. Le changement sera effectif après validation.',
  'danger_titre'        => '⚠ Supprimer mon compte',
  'danger_txt'          => 'Vos données personnelles (nom, adresse, téléphone, IBAN) seront effacées. Votre historique de dons sera conservé de façon anonyme pour nos obligations comptables légales. <strong>Cette action est irréversible.</strong>',
  'btn_demander_suppression' => 'Demander la suppression de mon compte',
  'confirm_suppression_label' => 'Tapez SUPPRIMER pour confirmer :',
  'confirm_suppression_ph'    => 'SUPPRIMER',
  'btn_supprimer'       => '🗑 Supprimer définitivement',
  'btn_annuler'         => 'Annuler',
  'btn_deconnecter'     => '⎋ Se déconnecter',
  'actualiser_qr'       => '🔄 Actualiser',
  'telecharger_qr'      => '⬇ Télécharger',
  'libre'               => 'Libre',
  'montant_ph'          => 'Montant €',
];

// Raccourci
function tm(string $key, ...$args): string {
    global $T;
    $val = $T[$key] ?? "[$key]";
    return $args ? vsprintf($val, $args) : $val;
}
